#!/bin/bash

export ROOT=${BUILDKITE_BUILD_CHECKOUT_PATH:-$PWD}
export PATH=$PATH:$ROOT/node_modules/.bin

if [[ "$1" =~ ^(android|ios)$ ]]; then export PLATFORM=$1; shift; fi
if [[ "$1" =~ ^[a-z,]+$ ]]; then SCRIPTS=$1; shift;
else echo "Invalid script $1"; exit 1; fi

ARGS=$@

export BUILD_PROFILE=beta

while true; do
case $1 in
  -p|--profile)
  export BUILD_PROFILE=$2
  shift; shift;;
  '') break;;
  *) shift;;
esac
done

run() {
  set +eu
  script=$1; shift;
  if [[ -f $ROOT/.circleci/$script.sh ]]; then
    source $ROOT/.circleci/$script.sh $@
  fi
  if [[ $PLATFORM && -f $ROOT/.circleci/$PLATFORM/$script.sh ]]; then
    $ROOT/.circleci/$PLATFORM/$script.sh $@
  fi
}

export -f run

echo $SCRIPTS | tr "," " " | xargs -n1 -I{} bash -c "run \$@ $ARGS" - {}
