#!/bin/bash

export MIX_ENV=e2e

if [ ! -f "$PWD/backend/mix.lock" ];
then git submodule update --init; fi

cp -r __e2e__/server/* backend
pushd backend
  mix deps.get
  mix ecto.drop
  mix ecto.create
  mix ecto.migrate
  mix run priv/repo/seeds.e2e.exs
  mix phx.server
popd
